run:
  concurrency: 2
  timeout: 10m
linters:
  enable-all: false
  disable-all: true
  enable:
    - depguard
    - errcheck
    - errorlint
    - gocyclo
    - goimports
    - gomodguard
    - revive
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - staticcheck
    - testifylint
    - typecheck
    - unconvert
    - unparam
    - unused
linters-settings:
  revive:
    rules:
      - name: package-comments
        disabled: true
  depguard:
    rules:
      all:
        deny:
          - pkg: io/ioutil
            desc: 'io/ioutil package has been deprecated'
          - pkg: gopkg.in/yaml.v2
            desc: 'use yaml.v3'
  gomodguard:
    blocked:
      modules:
        - github.com/pkg/errors:
            recommendations:
              - errors
              - fmt
  gocyclo:
    min-complexity: 16
issues:
  # golangci hides some golint warnings (the warning about exported things
  # without documentation for example), this will make it show them anyway.
  exclude-use-default: false
  # Maximum issues count per one linter.
  # Set to 0 to disable.
  # Default: 50
  max-issues-per-linter: 0
  # Maximum count of issues with the same text.
  # Set to 0 to disable.
  # Default: 3
  max-same-issues: 0
