// beholder - Copyright © 2024 Philipp Milovic
//
// SPDX-License-Identifier: Apache-2.0

#include "beholder/camera/pylon/Camera.h"

#include <incbin/incbin.h>

#include <array>
#include <cassert>
#include <cstddef>
#include <cstdlib>
#include <filesystem>
#include <iostream>
#include <memory>
#include <optional>

#include "beholder/camera/DeviceClass.h"
#include "beholder/camera/Parameter.h"
#include "beholder/camera/TriggerType.h"
#include "beholder/camera/pylon/shim/API.h"	 // NOLINT
#include "beholder/camera/pylon/shim/Camera.h"
#include "beholder/camera/pylon/shim/TransportLayer.h"
#include "beholder/capi/Image.h"
#include "beholder/embed/Loader.h"
#include "beholder/embed/Unpacker.h"
#include "beholder/util/Enums.h"

#ifndef BH_PYLON_EMBED_DIR
#error "BH_PYLON_EMBED_DIR not defined"
#endif

INCBIN(Pylon, BH_PYLON_EMBED_DIR "/pylonshim.tar.gz");

namespace fs = std::filesystem;

namespace beholder {
namespace camera {
namespace pylon {

const fs::path ShimLib{"libpylonshim"};	 // pylon shim library

// Pylon shared libraries, in load order.
//
// The order is reversed from the conventional load order: the base
// libraries get loaded first, and then the dependent libraries.
// This is because some of the pylon libraries also dynamically load their
// dependent libraries, and since we're creating the shared object files at
// a temporary location during program startup, we need to ensure that all
// libraries are known/available to the dynamic loader before any dependent
// library tries to load one of them.
//
// That is, when libA tries to dynamically load libB (the location of libB
// is not on the default search path, because we've created it in some
// temporary directory), we must ensure that libB is already loaded, i.e.,
// known to the dynamic loader. Hence, we load libB first, then libA, and
// lazily resolve symbols.
//
// TODO: the library names should maybe get generated by/pulled from CMake, but
// this might cause issues with ensuring correct load ordering (we glob so the
// ordering might get mangled).
const std::array<fs::path, 16> Libs{"libGCBase_gcc_v3_1_Basler_pylon",
									"libMathParser_gcc_v3_1_Basler_pylon",
									"libgxapi",
									"libuxapi",
									"libNodeMapData_gcc_v3_1_Basler_pylon",
									"liblog4cpp_gcc_v3_1_Basler_pylon",
									"libLog_gcc_v3_1_Basler_pylon",
									"libXmlParser_gcc_v3_1_Basler_pylon",
									"libGenApi_gcc_v3_1_Basler_pylon",
									"libFirmwareUpdate_gcc_v3_1_Basler_pylon",
									"libpylon_TL_gige",
									"libpylon_TL_camemu",
									"libpylonbase",
									"libpylonutility",
									"libpylonc",
									ShimLib};

CamPtr createCamera(DeviceClass dc) { return std::make_unique<Camera>(dc); }

Camera::Runtime::Runtime() noexcept
	: upk{gPylonData, gPylonSize},
	  ldr{embed::Loader::matchPaths(upk.getFiles(), Libs)},
	  api{[](const embed::Loader& l) -> APIHandle {
		  APIHandle a{l.getClass<APIHandle::element_type>(
			  ShimLib, "pylonAPI_create", "pylonAPI_delete")};

		  assert(a != nullptr && "Failed to load pylonshim::API symbol");
		  return a;
	  }(ldr)},
	  tls{[](const embed::Loader& l) -> TLArray {
		  TLArray arr{};
		  for (auto& a : arr) {
			  // NOLINTNEXTLINE(cppcoreguidelines-*)
			  a = l.getClass<TLHandle::element_type>(
				  ShimLib, "pylonTransportLayer_create",
				  "pylonTransportLayer_delete");

			  assert(a != nullptr &&
					 "Failed to load pylonshim::TransportLayer symbol");
		  }
		  return arr;
	  }(ldr)} {}

Camera::Camera(DeviceClass dc) : dc_{dc} {
	if (dc_ != DeviceClass::GigE && dc_ != DeviceClass::Emulated) {
		std::cerr << "bad device class: " << enums::to(dc_) << std::endl;
		std::exit(EXIT_FAILURE);
	}
	if (!runtime_) {
		runtime_ = std::make_unique<Runtime>();
	}
	++runtime_->count;

	cam_ = runtime_->ldr.getClass<CamHandle::element_type>(
		ShimLib, "pylonCamera_create", "pylonCamera_delete");

	assert(cam_ != nullptr && "Failed to load pylonshim::Camera symbol");
}

Camera::~Camera() {
	cam_.reset();
	if (runtime_ && --runtime_->count == 0) {
		runtime_.reset();
	}
}

bool Camera::init(const char* designator, Milliseconds timeout,
				  bool reboot) noexcept {
	bool ok{true};
	// NOLINTNEXTLINE(*-pro-bounds-constant-array-index)
	TLHandle& tl{runtime_->tls[enums::to(dc_)]};
	if (!tl->isInitialized()) {
		ok = ok && tl->init(dc_);
	}
	if (ok && !cam_->isInitialized()) {
		ok = ok && cam_->init(tl->createDevice(designator, timeout, reboot));
	}
	return ok;
}

ParamVector Camera::getParams(Parameter::AccessMode mode) noexcept {
	return cam_->getParams(mode);
}

bool Camera::setParams(CParamSpan params) noexcept {
	return cam_->setParams(params);
}

bool Camera::trigger([[maybe_unused]] TriggerType typ) noexcept {
	return cam_->trigger();
}

bool Camera::waitAndTrigger(Milliseconds timeout,
							[[maybe_unused]] TriggerType typ) noexcept {
	return cam_->waitAndTrigger(timeout);
}

bool Camera::acquire(Milliseconds timeout) noexcept {
	return cam_->acquire(timeout);
}

bool Camera::startAcquisition(size_t nImages) noexcept {
	return cam_->startAcquisition(nImages);
}

void Camera::stopAcquisition() noexcept { cam_->stopAcquisition(); }

bool Camera::isAcquiring() const noexcept { return cam_->isAcquiring(); }

bool Camera::isInitialized() const noexcept { return cam_->isInitialized(); }

bool Camera::isAttached() const noexcept { return cam_->isAttached(); }

std::optional<Image> Camera::getImage() noexcept { return cam_->getImage(); }

bool Camera::cmdExecute(const char* cmd) noexcept {
	return cam_->cmdExecute(cmd);
}

bool Camera::cmdIsDone(const char* cmd) noexcept {
	return cam_->cmdIsDone(cmd);
}

}  // namespace pylon
}  // namespace camera
}  // namespace beholder
