# This workflow builds a base image containing packages and  third-party
# dependencies used by both the C-API and the final beholder binary during
# the build phase.

name: build base image

on:
  workflow_call:
    inputs:
      dockerhub-username:
        type: string
        required: true
      gcc-version:
        type: string
        required: false
        default: 12
      clang-version:
        type: string
        required: false
        default: 14
      staging-dir:
        type: string
        required: false
        default: '/usr/local'
      skip-build:
        type: boolean
        required: false
        default: false
    outputs:
      image:
        description: "Digest of the pushed Docker image"
        value: ${{ jobs.build.outputs.image }}
    secrets:
      dockerhub-token:
        required: true

env:
  IMAGE: ${{ inputs.dockerhub-username }}/beholder-third-party:latest

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    outputs:
      image: ${{ inputs.skip-build == true && env.IMAGE || steps.build.outputs.digest }}
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.dockerhub-username}}
          password: ${{ secrets.dockerhub-token}}

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      # we specifically don't cache anything
      - name: Docker build and push
        id: build
        if: ${{ inputs.skip-build == false }}
        uses: docker/build-push-action@v6
        with:
          push: true
          file: build/ci/beholder.Dockerfile
          build-args: |
            gcc_version: ${{ inputs.gcc-version}}
            clang_version: ${{ inputs.clang-version}}
            staging_dir: ${{ inputs.staging-dir }}
            build_mode: release
            ci_build: true
          network: host
          target: builder-third-party
          tags: |
            ${{ env.IMAGE }}
