name: ci

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'build/ci/beholder.Dockerfile'
      - 'build/ci/beholder.Dockerfile.dockerignore'
      - '_c-api/third_party/**'
      - '.github/workflows/base_image.yml'
      - '*.md'
  workflow_dispatch:

env:
  GOLANGCI_VERSION: '1.63.4'
  CMAKE_PREFIX: '/usr/local'

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        cfg:
          #- { id: amd64-clang-debug,   base_tag: amd64-gnu,  cmake_preset: debug,   build_flags: '-asan' }
          #- { id: amd64-clang-release, base_tag: amd64-gnu,  cmake_preset: release, build_flags: '' }
          #- { id: amd64-gnu-debug,   base_tag: amd64-gnu,  cmake_preset: debug,   build_flags: '-asan' }
          - { id: amd64-gnu-release, base_tag: amd64-gnu,  cmake_preset: release, build_flags: '' }

    container:
      image: ${{ vars.DOCKERHUB_USERNAME }}/beholder-third-party:${{ matrix.cfg.base_tag }}
      credentials:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
          cache-dependency-path: |
            ./go.sum

      - name: Install Go modules
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go

      # FIXME: no caching and we lint every time we build, instead
      # of only once per workflow run
      - name: Build C-API
        run: |
          CMAKE_PREFIX=${{ env.CMAKE_PREFIX }} \
            CMAKE_PRESET=${{ matrix.cfg.cmake_preset }} \
            make c-api
          ldconfig

      - name: Test C-API
        run: |
          cd _c-api
          ctest --preset=${{ matrix.cfg.cmake_preset }}

      # FIXME: we should lint in an unrelated workflow
#      - name: Lint beholder
#        uses: golangci/golangci-lint-action@v6
#        with:
#          version: v${{ env.GOLANGCI_VERSION }}

      - name: Build beholder
        run: |
          GO_FLAGS=${{ matrix.cfg.build_flags }} make build

      # FIXME: package 'server' tests should use '-count > 1'
      - name: Test beholder
        run: |
          GO_FLAGS="${{ matrix.cfg.build_flags }} -race" make test
