name: ci

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  GCC_VERSION: 12
  CLANG_VERSION: 14
  GOLANGCI_VERSION: '1.63.4'
  STAGING_DIR: '/usr/local'

jobs:
  changes:
    runs-on: ubuntu-24.04
    permissions:
      pull-request: read
    outputs:
      third-party: ${{ steps.filter.outputs.third-party }}
      c-api: ${{ steps.filter.outputs.c-api }}
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            third-party:
              - 'build/ci/beholder.Dockerfile'
              - '_c-api/third_party/**'
            beholder:
              - '_c-api/**'
              - '!_c-api/third_party/**'
              - 'go.mod'
              - 'go.sum'
              - 'main.go'
              - 'cmd/**'
              - 'internal/**'

  # build and push base container image
  third-party:
    needs: changes
    runs-on: ubuntu-24.04
    steps:
      uses: ./.github/workflows/base_image.yml
      with:
        skip-build: ${{ needs.changes.outputs.third-party == 'false' }}
        gcc-version: ${{ env.GCC_VERSION }}
        clang-version: ${{ env.CLANG_VERSION }}
        staging-dir: ${{ env.STAGING_DIR }}
        dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
      secrets:
        dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

  # build and test beholder
  beholder:
    needs: [changes, third-party]
    if: ${{ needs.changes.outputs.beholder == 'true' }}
    runs-on: ubuntu-24.04
    steps:
      uses: ./.github/workflows/build.yml
      with:
        docker-image: ${{ needs.third-party.outputs.image }}
        golangci-version: ${{ env.GOLANGCI_VERSION }}
        staging-dir: ${{ env.STAGING_DIR }}
        dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
      secrets:
        dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
